### ISSUE TITLE
mlvp优化建议

### ISSUE THREAD

**Issue by chen1287** [XS-MLVP/mlvp#4]
1：优化Bundle的报错逻辑，在连接\未连接的提醒上加上bundle的前缀
2：框架中是否可以增加s2和s3的预测输入

**Comment by Miical** [comment]
Bundle 报错信息待优化
s2和s3预测输入是FTQ环境的问题，不是mlvp所属问题

**Comment by chen1287** [comment]
收到！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月24日(周五) 下午3:51
收件人: ***@***.***&gt;;
抄送: "Xiao ***@***.******@***.***&gt;;
主题: Re: [XS-MLVP/mlvp] mlvp优化建议 (Issue #4)




 
Bundle 报错信息待优化
 s2和s3预测输入是FTQ环境的问题，不是mlvp所属问题

**Comment by Miical** [comment]
新 Bundle 中已实现
